#ifndef ERROR_TYPE
#define ERROR_TYPE

enum ErrorType
{
    VAR_UNDEFINED = 1,
    FUNC_UNDEFINED,
    VAR_REDEFINATION,
    FUNC_REDEFINATION,
    EXP_TYPE_MISMATCH,
    RVALUE_ASSIGNED,
    OPERAND_TYPE_MISMATCH,
    RETURN_VALUE_MISMATCH,
    PAR_ARG_MISMATCH,
    ARRAY_OP_MISUSED = 10,
    CALL_OP_MISUSED,
    NONINTEGER_IN_ARRAY_OP,
    ACCESS_MEMBER_OF_NONSTRUCT,
    VISIT_UNDEFINED_STRUCT_MEMBER,
    STRUCT_MEMBER_DEFINED_INVALID,
    STRUCT_NAME_REPEATED,
    UNDEFINED_STRUCT = 17,
    FUNC_DECLARED_BUT_UNDEFINED,
    INCONSISTENT_DECLARATION,
    FUNC_HAS_NO_RET_VALUE
};

#endif